/**
 * Security Model: API keys are safe to expose in client-side code (Firebase
 * restricts access via domain whitelist + Firestore Security Rules). For
 * production, consider moving to environment variables (import.meta.env.VITE_*).
 *
 * Generated by: Firebase Console > Project Settings (do not manually edit keys)
 */
import { initializeApp } from 'firebase/app'

const required = [
  'VITE_FIREBASE_API_KEY',
  'VITE_FIREBASE_AUTH_DOMAIN',
  'VITE_FIREBASE_PROJECT_ID',
  'VITE_FIREBASE_STORAGE_BUCKET',
  'VITE_FIREBASE_MESSAGING_SENDER_ID',
  'VITE_FIREBASE_APP_ID'
]

const env = import.meta.env as Record<string, string | undefined>
// Fail-fast guard
required.forEach((key) => {
  if (!env[key]) {
    throw new Error(`Missing environment variable: ${key}`)
  }
})

// Firebase Console Configuration (production)
// Domain whitelist enforced: defi-scout.firebaseapp.com, localhost:5173
const firebaseConfig = {
  apiKey: env.VITE_FIREBASE_API_KEY,
  authDomain: env.VITE_FIREBASE_AUTH_DOMAIN,
  projectId: env.VITE_FIREBASE_PROJECT_ID,
  storageBucket: env.VITE_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: env.VITE_FIREBASE_MESSAGING_SENDER_ID,
  appId: env.VITE_FIREBASE_APP_ID
}

// Initialize Firebase (runs once on module load)
export const app = initializeApp(firebaseConfig)
