/**
 * Security Model: API keys are safe to expose in clien-side code (Firebase
 * restricts access via domain whitelist + Firestore Security Rules). For
 * production, consider moving to environment variables (import.meta.env.VITE_*).
 *
 * Generated by: Firebase Console > Project Settings (do not manually edit keys)
 */
import { initializeApp } from 'firebase/app'
import { getAuth } from 'firebase/auth'
import { getFirestore } from 'firebase/firestore'

// Firebase Console Configuration (production)
// Domain whitelist enforced: defi-scout.firebaseapp.com, localhost:5173
const firebaseConfig = {
  apiKey: 'AIzaSyC_bxb1jWSZb3wcPGpQNRSX8yzBp0X0dL8',
  authDomain: 'defi-scout.firebaseapp.com',
  projectId: 'defi-scout',
  storageBucket: 'defi-scout.firebasestorage.app',
  messagingSenderId: '631537599201',
  appId: '1:631537599201:web:c831a25a3cc327a6616da0',
}

// Initialize Firebase (runs once on module load)
const app = initializeApp(firebaseConfig)

/**
 * Singleton: Firestore Authentication instance.
 * Import this in components instead of calling getAuth() multiple times.
 * @type {Auth}
 */
export const auth = getAuth(app)

/**
 * Singleton: Firestore Database instance.
 * Import this in components instead of calling getFirestore() multiple times.
 * @type {Firestore}
 */
export const db = getFirestore(app)
